name: Auto Merge Dependabot

on:
  workflow_run:
    types:
      - completed
    workflows:
      # List all required workflow names here.
      - 'Node.js CI'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    permissions:
      pull-requests: write
      contents: write

    steps:
    - name: Set Timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/London"
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: automerge
      env:
        PR_NUMBER: ${{ github.event.number }}
      uses: fastify/github-action-merge-dependabot@v3
      with:
        pr-number: ${{ github.event.number }}
